### ISSUE TITLE
Cannot open the Tutorial.nb noramlly

### ISSUE THREAD

**Issue by Juddd** [noahbenson/Neurotica#2]
This is v10.4.1 on windows 10.When I open the Tutorial.nb,I will give a warning like

![](http://o8aucf9ny.bkt.clouddn.com/2016-06-16-14-38-25.png) 

Then I click the `Yes`,I get

![](http://o8aucf9ny.bkt.clouddn.com/2016-06-16-17-35-50.png) 

So is this normal?

**Comment by szhorvat** [comment]
Looks like an unresolved merge conflict got accidentally committed.

@noahbenson To make it easier to handle notebooks in version control, you might find it useful to turn off cell history tracking and the file outline cache.  
- Go to Cell -> Notebook History -> uncheck  "Track notebook history" and click "Clear History"
- Then go to Format -> Option Inspector, in the first dropdown choose "Selected Notebook", then under Notebook Options -> PrivateNotebookOptions, set "FileOutlineCache" to False.

Doing this reduced the number of invisible changes that the front end makes to the notebook, therefore it reduces the likelihood of a merge conflict too.

**Comment by noahbenson** [comment]
This should be fixed now; thanks for finding this, Juddd, and for the suggestions, szhorvat.
