### ISSUE TITLE
Is there any way to export a NIFTI file after it has been imported and edited? 

### ISSUE THREAD

**Issue by Bassir** [noahbenson/Neurotica#4]
I have used the NIFTI import feature to import a NIFTI data file as "voxels", and then modified the 3D array contained in the NIFTI. I wish to now export the data as a NIFTI file with the same header as the initial file, effectively using Mathematica as a NIFTI editor. 

I know there is no export nifti function, so is there any simple way to reverse-engineer the import function to do this?

**Comment by noahbenson** [comment]
Neurotica doesn't support this currently, and it's unlikely that I will add it in the near future (though if someone wants to write a good NIFTI exporter I'd be happy to field a pull request). There is no simple way to reverse engineer an import function, either. If you have FreeSurfer installed (https://surfer.nmr.mgh.harvard.edu/) my recommendation would be to use its mri_convert command to convert your NIFTI to an MGH file then import/edit/export it using Neurotica, and mri_convert it back to a NIFTI. You could also consider looking at the NIFTI import code in Neurotica (or the official NIFTI file format spec) and figuring out just where in your NIFTI file the voxel data lies, then opening and writing those bytes into your file directly; though this will probably require figuring out the correct ordering of the dimensions, which is not always the same as the way dimensions are ordered in Mathematica after importing.
Unfortunately, I do not do a lot of work on Neurotica these days as I'm moving most of my research over from Mathematica to Python, which is more widely used in neuroscience and is open source.
One last note: Wolfram really ought to provide NIFTI import and export functions natively; they have many examples/tutorials dealing with MRI data, and they claim in publicity material that Mathematica is appropriate for MRI data analysis. I would suggest lobbying Wolfram directly to add this feature.
